name: Test

on:
  push:
    branches: [ main, internal-release, develop ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  test:
    runs-on: [self-hosted, macos]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Display JDK information
      run: |
        echo "==== JDK Information ===="
        java -version
        echo "JDK path: $JAVA_HOME"
        echo "========================="
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run tests with JavaFX-enabled JDK
      run: |
        echo "Running tests with $(java -version 2>&1 | head -1)"
        ./gradlew test --no-daemon
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          app/build/test-results/
          app/build/reports/tests/
        retention-days: 30  