name: Test

on:
  push:
    branches: [ main, internal-release, develop ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Liberica JDK 21 Full with JavaFX
      uses: actions/setup-java@v4
      with:
        distribution: 'liberica'
        java-version: '21.0.7' # Specific version to avoid extraction issues
        java-package: 'jdk+fx' # This selects liberica-jdk-21-full with JavaFX built-in
        cache: 'gradle'
        check-latest: false # Don't try to get latest version
      
    - name: Display JDK information
      run: |
        echo "==== JDK Information ===="
        java -version
        echo "JDK path: $JAVA_HOME"
        echo "========================="
        
    - name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run tests with JavaFX-enabled JDK
      run: |
        echo "Running tests with $(java -version 2>&1 | head -1)"
        ./gradlew test --no-daemon
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          app/build/test-results/
          app/build/reports/tests/
        retention-days: 30  