name: Test

on:
  push:
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21 (Amazon Corretto)
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        
    - name: Display JDK information
      run: |
        echo "==== JDK Information ===="
        java -version
        echo "JDK path: $JAVA_HOME"
        echo "========================="
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Run tests
      run: |
        echo "Running tests with $(java -version 2>&1 | head -1)"
        ./gradlew test --no-daemon
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          app/build/test-results/
          app/build/reports/tests/
        retention-days: 30  